# yaml for acr build and push 

trigger:
  none

pool:
  name: javashpool
  demands:
    - agent.name -equals javashagent

stages:
  - stage: mavenCompile # Stage name should ideally have a unique identifier.
    displayName: 'Maven Compile'
    jobs:
      - job: compile
        displayName: 'Compile Maven Project' # Adding a displayName for the job for clarity.
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Free Trial(9316ffff-5798-4604-8dce-fc0fc04595f9)'
            mavenPomFile: 'Boardgame/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
