# yaml for acr build and push 

trigger:
  none

pool:
  name: javashpool
  demands:
    - agent.name -equals javashagent

stages:
  - stage: mavenCompile # Stage name should ideally have a unique identifier.
    displayName: 'Maven Compile'
    jobs:
      - job: compile
        displayName: 'Compile Maven Project' # Adding a displayName for the job for clarity.
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'Boardgame/pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

  - stage: mavenPackage # Stage name should ideally have a unique identifier.
    displayName: 'Maven Package'
    jobs:
      - job: package
        displayName: 'package Maven Project' # Adding a displayName for the job for clarity.
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'Boardgame/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false



